package frames

import "time"

// DataFrame is the base for all data-carrying frames
type DataFrame struct {
	*BaseFrame
}

func (f *DataFrame) Category() FrameCategory {
	return DataCategory
}

// TextFrame carries text content through the pipeline
type TextFrame struct {
	*DataFrame
	Text string
	// SkipTTS mirrors LLMTextFrame.SkipTTS — set by SentenceAggregator when
	// the source LLMTextFrame had SkipTTS=true.
	SkipTTS bool
}

func NewTextFrame(text string) *TextFrame {
	return &TextFrame{
		DataFrame: &DataFrame{
			BaseFrame: NewBaseFrame("TextFrame"),
		},
		Text: text,
	}
}

// AudioFrame carries raw audio data
type AudioFrame struct {
	*DataFrame
	Data       []byte
	SampleRate int
	Channels   int
}

func NewAudioFrame(data []byte, sampleRate, channels int) *AudioFrame {
	return &AudioFrame{
		DataFrame: &DataFrame{
			BaseFrame: NewBaseFrame("AudioFrame"),
		},
		Data:       data,
		SampleRate: sampleRate,
		Channels:   channels,
	}
}

// TranscriptionFrame carries speech-to-text results
type TranscriptionFrame struct {
	*DataFrame
	Text      string
	IsFinal   bool
	Language  string
	Timestamp time.Time
}

func NewTranscriptionFrame(text string, isFinal bool) *TranscriptionFrame {
	return &TranscriptionFrame{
		DataFrame: &DataFrame{
			BaseFrame: NewBaseFrame("TranscriptionFrame"),
		},
		Text:      text,
		IsFinal:   isFinal,
		Timestamp: time.Now(),
	}
}

// IsTranscriptionFinal satisfies the finalTranscriptionProvider interface used by
// SpeechTimeoutUserTurnStopStrategy to trigger immediate turn stops when a final
// transcript arrives while the turn timer is running.
func (f *TranscriptionFrame) IsTranscriptionFinal() bool {
	return f.IsFinal
}

// LLMTextFrame carries text generated by an LLM
type LLMTextFrame struct {
	*DataFrame
	Text string
	// SkipTTS, when true, instructs TTS services to skip synthesis for this
	// frame. Used by UserTurnCompletionProcessor to suppress TTS for frames
	// that should be stored in context but not spoken (e.g. ○/◐ turn markers).
	SkipTTS bool
}

func NewLLMTextFrame(text string) *LLMTextFrame {
	return &LLMTextFrame{
		DataFrame: &DataFrame{
			BaseFrame: NewBaseFrame("LLMTextFrame"),
		},
		Text: text,
	}
}

// TTSAudioFrame carries synthesized speech audio
type TTSAudioFrame struct {
	*DataFrame
	Data       []byte
	SampleRate int
	Channels   int
	ContextID  string
}

func NewTTSAudioFrame(data []byte, sampleRate, channels int) *TTSAudioFrame {
	return &TTSAudioFrame{
		DataFrame: &DataFrame{
			BaseFrame: NewBaseFrame("TTSAudioFrame"),
		},
		Data:       data,
		SampleRate: sampleRate,
		Channels:   channels,
	}
}

// STTMetadataFrame carries STT service metadata for auto-tuning turn detection
type STTMetadataFrame struct {
	*DataFrame
	Provider       string        // STT provider name (e.g., "deepgram", "whisper", "azure")
	TTFSP99Latency time.Duration // P99 time-to-final-segment latency
}

type TurnMetricsFrame struct {
	*DataFrame
	ProcessorName string
	StartTime     time.Time
	EndTime       time.Time
	Duration      time.Duration
}

func NewTurnMetricsFrame(processorName string, startTime, endTime time.Time, duration time.Duration) *TurnMetricsFrame {
	return &TurnMetricsFrame{
		DataFrame: &DataFrame{
			BaseFrame: NewBaseFrame("TurnMetricsFrame"),
		},
		ProcessorName: processorName,
		StartTime:     startTime,
		EndTime:       endTime,
		Duration:      duration,
	}
}

func NewSTTMetadataFrame(provider string, p99 time.Duration) *STTMetadataFrame {
	return &STTMetadataFrame{
		DataFrame: &DataFrame{
			BaseFrame: NewBaseFrame("STTMetadataFrame"),
		},
		Provider:       provider,
		TTFSP99Latency: p99,
	}
}

// GetTTFSP99Latency returns the P99 latency (satisfies sttLatencyProvider interface in user_stop)
func (f *STTMetadataFrame) GetTTFSP99Latency() time.Duration {
	return f.TTFSP99Latency
}
