package frames

import "time"

// DataFrame is the base for all data-carrying frames
type DataFrame struct {
	*BaseFrame
}

func (f *DataFrame) Category() FrameCategory {
	return DataCategory
}

// TextFrame carries text content through the pipeline
type TextFrame struct {
	*DataFrame
	Text string
}

func NewTextFrame(text string) *TextFrame {
	return &TextFrame{
		DataFrame: &DataFrame{
			BaseFrame: NewBaseFrame("TextFrame"),
		},
		Text: text,
	}
}

// AudioFrame carries raw audio data
type AudioFrame struct {
	*DataFrame
	Data       []byte
	SampleRate int
	Channels   int
}

func NewAudioFrame(data []byte, sampleRate, channels int) *AudioFrame {
	return &AudioFrame{
		DataFrame: &DataFrame{
			BaseFrame: NewBaseFrame("AudioFrame"),
		},
		Data:       data,
		SampleRate: sampleRate,
		Channels:   channels,
	}
}

// TranscriptionFrame carries speech-to-text results
type TranscriptionFrame struct {
	*DataFrame
	Text      string
	IsFinal   bool
	Language  string
	Timestamp time.Time
}

func NewTranscriptionFrame(text string, isFinal bool) *TranscriptionFrame {
	return &TranscriptionFrame{
		DataFrame: &DataFrame{
			BaseFrame: NewBaseFrame("TranscriptionFrame"),
		},
		Text:      text,
		IsFinal:   isFinal,
		Timestamp: time.Now(),
	}
}

// LLMTextFrame carries text generated by an LLM
type LLMTextFrame struct {
	*DataFrame
	Text string
}

func NewLLMTextFrame(text string) *LLMTextFrame {
	return &LLMTextFrame{
		DataFrame: &DataFrame{
			BaseFrame: NewBaseFrame("LLMTextFrame"),
		},
		Text: text,
	}
}

// TTSAudioFrame carries synthesized speech audio
type TTSAudioFrame struct {
	*DataFrame
	Data       []byte
	SampleRate int
	Channels   int
}

func NewTTSAudioFrame(data []byte, sampleRate, channels int) *TTSAudioFrame {
	return &TTSAudioFrame{
		DataFrame: &DataFrame{
			BaseFrame: NewBaseFrame("TTSAudioFrame"),
		},
		Data:       data,
		SampleRate: sampleRate,
		Channels:   channels,
	}
}
